import Link from "next/link";

export const metadata = {
  title: "Terms of Service — Telesto Node",
};

function Section({ title, children }) {
  return (
    <div className="mb-6">
      <h2 className="text-cyan-400 text-sm uppercase tracking-widest mb-2">{title}</h2>
      <div className="text-cyan-100/90 text-sm leading-relaxed space-y-2">{children}</div>
    </div>
  );
}

export default function TermsOfService() {
  return (
    <div className="min-h-screen bg-black text-cyan-200 font-mono px-6 py-12">
      <div className="max-w-2xl mx-auto">
        <Link
          href="/login"
          className="text-xs text-cyan-400/70 hover:text-cyan-300 mb-8 inline-block"
        >
          ← Back to Sign In
        </Link>

        <h1 className="text-2xl font-bold mb-1">Terms of Service</h1>
        <p className="text-xs text-cyan-400/60 mb-8">Last updated: July 2026</p>

        <Section title="1. Acceptance of Terms">
          <p>
            By creating an account or otherwise using Telesto Node ("the Service"), you agree
            to these Terms of Service. If you do not agree, please do not use the Service.
          </p>
        </Section>

        <Section title="2. Description of Service">
          <p>
            Telesto Node is a real-time marine ecosystem monitoring and analytics tool. It
            provides computer-vision species detection, coral bleaching analysis, 3D bathymetry
            visualization, and mission report generation, using video footage supplied by the
            user (via file upload, live webcam, or a linked URL) and third-party data sources
            (including Roboflow-hosted inference models, the Ocean Biodiversity Information
            System (OBIS), and Open-Meteo's marine weather data).
          </p>
        </Section>

        <Section title="3. Research & Educational Use Only">
          <p>
            The Service is intended for research, educational, and demonstration purposes.
            Detections, species identifications, coral health scores, and telemetry readings
            are generated by automated models and heuristics that may be inaccurate or
            incomplete. Telesto Node must not be relied upon for navigation, safety-critical
            decisions, conservation enforcement, or any purpose where an incorrect reading
            could cause harm.
          </p>
        </Section>

        <Section title="4. Accounts">
          <p>
            You may sign in using Google OAuth or an email/password account you create. You are
            responsible for maintaining the confidentiality of your credentials and for all
            activity under your account. Notify us if you suspect unauthorized access.
          </p>
        </Section>

        <Section title="5. Your Content">
          <p>
            Video footage you upload, stream from a webcam, or link via URL is processed to
            generate detections and reports. Uploaded and webcam footage is processed in your
            browser session and is not permanently stored by the Service unless a future
            feature (e.g. discovery snapshots) explicitly says otherwise. You are responsible
            for ensuring you have the right to use and analyze any footage you provide,
            including footage sourced from third parties (e.g. NOAA Ocean Exploration's public
            domain archive).
          </p>
        </Section>

        <Section title="6. Third-Party Services">
          <p>
            The Service relies on several third-party providers, each governed by their own
            terms: Google (authentication), Roboflow (hosted computer vision inference), MongoDB
            Atlas (data storage), Open-Meteo (marine weather data), and OBIS (species occurrence
            records). Telesto Node is not responsible for the availability, accuracy, or
            practices of these third parties.
          </p>
        </Section>

        <Section title="7. Acceptable Use">
          <p>You agree not to use the Service to:</p>
          <ul className="list-disc list-inside space-y-1">
            <li>Upload or stream unlawful, harmful, or infringing content</li>
            <li>Attempt to disrupt, overload, or gain unauthorized access to the Service or its
              underlying infrastructure</li>
            <li>Use the video-URL proxy feature to access content you do not have the right to
              retrieve, or to circumvent another service's access controls</li>
            <li>Misrepresent automated detections as verified scientific fact in a way that
              could mislead conservation or policy decisions</li>
          </ul>
        </Section>

        <Section title="8. No Warranty">
          <p>
            The Service is provided "as is" without warranties of any kind, express or implied,
            including accuracy, reliability, or fitness for a particular purpose. Simulated
            telemetry values (depth, salinity, heading) are illustrative only and do not reflect
            real sensor hardware unless explicitly integrated.
          </p>
        </Section>

        <Section title="9. Limitation of Liability">
          <p>
            To the fullest extent permitted by law, Telesto Node and its creators shall not be
            liable for any indirect, incidental, or consequential damages arising from your use
            of, or inability to use, the Service.
          </p>
        </Section>

        <Section title="10. Changes to These Terms">
          <p>
            These Terms may be updated from time to time. Continued use of the Service after
            changes are posted constitutes acceptance of the revised Terms.
          </p>
        </Section>

        <Section title="11. Contact">
          <p>
            Questions about these Terms can be directed to the project maintainer through the
            Telesto Node repository.
          </p>
        </Section>
      </div>
    </div>
  );
}